language: csharp
dist: trusty
mono: none
dotnet: 2.2

before_install:
- sudo apt-get clean
- sudo apt-get update
- sudo apt-get install dpkg

install:
- dotnet restore

script:
- dotnet build
- dotnet test ScriptCompilerTests


